spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

server:
  port: ${SERVER_PORT:8082}

portfolio:
  service:
    url: ${PORTFOLIO_SERVICE_URL:https://pms-portfolio-service.fly.dev}

logging:
  level:
    com.wealthmanagement: INFO
    org.springframework.kafka: INFO
    org.springframework.data.mongodb: INFO
